baseURL = "https://qiong.me/"
languageCode = "zh-cn"
title = "ç©·.me"
theme = "Typo"


[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A tech-oriented personal blog curated by Francesco Tomaselli."

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = 'ç¢ç¢å¿µğŸ’¬'
homeIntroContent = """
æ–°é—»ä¸“ä¸šçœŸæ­£çš„é­”å¹»åœ¨äºï¼šå®ƒæ•™ä¼šä½ è§£æ„ä¸–ç•Œçš„è™šä¼ªï¼Œåˆé€¼ä½ æˆä¸ºè™šä¼ªçš„ä¸€éƒ¨åˆ†ã€‚ä½†æˆ–è®¸æ­£æ˜¯è¿™ç§æ’•è£‚æ„Ÿï¼Œè®©æ–°é—»äººéƒ½æˆäº†â€œæˆ´ç€é•£é“è·³èˆçš„æ¸…é†’è€…â€â€”â€”åœ¨ç®—æ³•ç›‘ç‹±é‡Œå†™å¯†ç è¯—ï¼Œç”¨æµé‡é¸¦ç‰‡ç†¬çœŸç†çš„æ±¤ã€‚
"""


singleDateFormat = '2006-01-02'

# Collection to display on home
homeCollectionTitle = 'éšç¬”é›†ğŸ“'
homeCollection = 'posts'

# Lists parameters
paginationSize = 10
listSummaries = false
listDateFormat = '2006-01-02'

# Breadcrumbs
breadcrumbs = true

showFooter = true
footerContent = """Custom"""

# Social icons
[[params.social]]
name = "twitter"
url = "https://www.x.com/22222/"

[[params.social]]
name = "telegram"
url = "https://t.me/fm789"

[[params.social]]
name = "github"
url = "https://github.com/ColinAZ"

# Main menu pages
[[params.menu]]
name = "ğŸ é¦–é¡µ"
url = "/"

[[params.menu]]
name = "ğŸ“‘æ–‡ç« "
url = "/posts"

[[params.menu]]
name = "ğŸ˜€å…³äº"
url = "/about"

[[params.menu]]
name = "æœ‹å‹"
url = "/friend"

# [[params.menu]]
# name = "tags"
# url = "/tags"


# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'bw'

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false
